### ISSUE TITLE
Events not found.

### ISSUE THREAD

**Issue by hmosousa** [aakanksha19/TDDiscourse#1]
Hi,

Thank you for making the dataset open source.

While cross-referencing TDDiscourse with TimeBank I found some events that are annotated on TDDAutoTrain.tsv but do not appear on TimeBank. The events I refer are the following:

- e3001 on ea980120.1830.0071
- e3000 on APW19980213.1310
- e3000 on AP900816-0139

Is there any reason for this?

**Comment by aakanksha19** [comment]
Hi, 

Thanks a lot for the question! The TDD-Auto data is automatically generated by applying heuristics to the dates assigned to events by the [Event-Time corpus](https://aclanthology.org/P16-1207.pdf). The Event-Time corpus has these additional events, which leads to the generation of event pairs containing them. Unfortunately, it looks like the corpus is no longer hosted on the UKP lab website, but I have an old copy that I can share with you if you would like to take a look at it. Hope this information helps, and feel free to ask any further clarification questions!

**Comment by hmosousa** [comment]
Hi Aakanksha,
Thanks for the (quick) responses. 
If you could share that copy would be very useful (my email is on my profile).
Thanks,
